app:
  persistence:
    provider: mysql
    endpoint: "project-bedrock-mysql.ci5e6eg2m2hx.us-east-1.rds.amazonaws.com:3306"
    database: "retailstore"
    secret:
      create: true
      username: admin
mysql:
  create: false
