ui:
  replicaCount: 1

catalog:
  mysql:
    create: false
    endpoint: "project-bedrock-mysql.ci5e6eg2m2hx.us-east-1.rds.amazonaws.com:3306"
    database: retailstore
    secret:
      create: true
      username: admin

orders:
  postgresql:
    create: false
    database: retailstore
    endpoint:
      host: "project-bedrock-postgres.ci5e6eg2m2hx.us-east-1.rds.amazonaws.com"
      port: "5432"
    secret:
      create: true
      username: dbadmin

carts:
  dynamodb:
    create: false
    createTable: true
